import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '📚 Introduction',
    },
    {
      type: 'category',
      label: '1️⃣ Module 1: Foundations',
      collapsed: false,
      items: [
        'module-01/intro',
        'module-01/week-01-02-physical-ai-intro',
        'module-01/week-03-05-ros2-fundamentals',
        'module-01/ros2-hands-on',
      ],
    },
    {
      type: 'category',
      label: '2️⃣ Module 2: Simulation',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'module-02/intro',
          label: 'Module Overview',
        },
      ],
    },
    {
      type: 'category',
      label: '3️⃣ Module 3: NVIDIA Isaac',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'module-03/intro',
          label: 'Module Overview',
        },
      ],
    },
    {
      type: 'category',
      label: '4️⃣ Module 4: Humanoid Robotics',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'module-04/intro',
          label: 'Module Overview',
        },
      ],
    },
    {
      type: 'category',
      label: '📖 Reference',
      collapsed: true,
      items: [
        'hardware',
        'resources',
        'glossary',
      ],
    },
  ],
};

export default sidebars;